CREATE TABLE "public"."a" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "a_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."a"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."todos"
  ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON SEQUENCE "public"."a_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."a_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."a_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."a_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."a_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."a_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."a_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."a_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."a" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."a" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."a" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."a" TO "service_role";

